## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [3]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()

  Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [6]:
# Create a list of at least 10 column names to use as X data

X_df = attrition_df[['Age', 'OverTime', 'DistanceFromHome', 'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction']]

# Create X_df using your selected columns

X_df.head()

# Show the data types for X_df

X_df.dtypes

Age                         int64
OverTime                   object
DistanceFromHome            int64
Education                   int64
EducationField             object
EnvironmentSatisfaction     int64
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobSatisfaction             int64
dtype: object

In [7]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

In [8]:
# Convert your X data to numeric data types however you see fit

X_df = pd.get_dummies(X_df)

X_df.head()

# Add new code cells as necessary

,Age,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,OverTime_No,OverTime_Yes,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree
0,41,1,2,2,94,3,2,4,False,True,False,True,False,False,False,False
1,49,8,1,3,61,2,2,2,True,False,False,True,False,False,False,False
2,37,2,2,4,92,2,1,3,False,True,False,False,False,False,True,False
3,33,3,4,4,56,3,1,3,False,True,False,True,False,False,False,False
4,27,2,1,1,40,3,1,2,True,False,False,False,False,True,False,False

In [10]:
# Create a StandardScaler
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=1)
StandardScaler = StandardScaler()
# Fit the StandardScaler to the training data
StandardScaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = StandardScaler.transform(X_train)
X_test_scaled = StandardScaler.transform(X_test)

In [11]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
department_encoder  = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
department_encoded = department_encoder.fit_transform(y_train['Department'].values.reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data
y_train_dept_encoded = pd.DataFrame(department_encoded, columns=department_encoder.get_feature_names_out(['Department']))
y_test_dept_encoded = pd.DataFrame(department_encoder.transform(y_test['Department'].values.reshape(-1, 1)), columns=department_encoder.get_feature_names_out(['Department']))

In [12]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
attrition_encoded = attrition_encoder.fit_transform(y_train['Attrition'].values.reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data

y_train_attrition_encoded = pd.DataFrame(attrition_encoded, columns=attrition_encoder.get_feature_names_out(['Attrition']))
y_test_attrition_encoded = pd.DataFrame(attrition_encoder.transform(y_test['Attrition'].values.reshape(-1, 1)), columns=attrition_encoder.get_feature_names_out(['Attrition']))

## Part 2: Create, Compile, and Train the Model

In [13]:
# Find the number of columns in the X training data.
no_of_columns = X_train_scaled.shape[1]
no_of_columns

# Create the input layer
input_layer = layers.Input(shape=(no_of_columns,))

# Create at least two shared layers
shared_layer1 = layers.Dense(units=64, activation='relu')(input_layer)
shared_layer2 = layers.Dense(units=32, activation='relu')(shared_layer1)

In [14]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer

department_hidden = layers.Dense(units=32, activation='relu')(shared_layer2)

# Create the output layer
department_output = layers.Dense(units=y_train_dept_encoded.shape[1], activation='softmax', name='department_output')(department_hidden)

In [15]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(units=32, activation='relu')(shared_layer2)

# Create the output layer
attrition_output = layers.Dense(units=y_train_attrition_encoded.shape[1], activation='softmax', name='attrition_output')(attrition_hidden)

In [16]:
# Create the model
model = Model(inputs=input_layer, outputs=[department_output, attrition_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'department_output':'categorical_crossentropy', 'attrition_output':'categorical_crossentropy'},
              metrics={'department_output':'accuracy', 'attrition_output':'accuracy'}
              )

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 16)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 64)        │      1,088 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 32)        │      2,080 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 32)        │      1,056 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 32)        │      1,056 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 3)         │         99 │ dense_2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 2)         │         66 │ dense_3[0][0]     │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 5,445 (21.27 KB)

 Trainable params: 5,445 (21.27 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
# Train the model

model.fit(X_train_scaled, [y_train_dept_encoded, y_train_attrition_encoded], epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - attrition_output_accuracy: 0.8509 - attrition_output_loss: 0.4716 - department_output_accuracy: 0.6142 - department_output_loss: 0.9292 - loss: 1.4012 - val_attrition_output_accuracy: 0.8281 - val_attrition_output_loss: 0.4846 - val_department_output_accuracy: 0.7285 - val_department_output_loss: 0.7537 - val_loss: 1.2413
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8408 - attrition_output_loss: 0.4221 - department_output_accuracy: 0.7744 - department_output_loss: 0.6726 - loss: 1.0948 - val_attrition_output_accuracy: 0.8190 - val_attrition_output_loss: 0.4566 - val_department_output_accuracy: 0.7330 - val_department_output_loss: 0.6793 - val_loss: 1.1389
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8741 - attrition_output_loss: 0.3364 - department_output_accuracy: 0.7532 - department_output_loss: 0.6234 - loss: 0.9597 - val_attrition_output_accuracy: 0.8281 - val_attrition_output_loss: 0.4523 - val_department_output_accuracy: 0.7376 - val_department_output_loss: 0.6527 - val_loss: 1.1085
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8717 - attrition_output_loss: 0.3375 - department_output_accuracy: 0.7675 - department_output_loss: 0.5875 - loss: 0.9251 - val_attrition_output_accuracy: 0.8281 - val_attrition_output_loss: 0.4717 - val_department_output_accuracy: 0.7511 - val_department_output_loss: 0.6256 - val_loss: 1.1009
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8661 - attrition_output_loss: 0.3304 - department_output_accuracy: 0.7937 - department_output_loss: 0.5367 - loss: 0.8670 - val_attrition_output_accuracy: 0.8281 - val_attrition_output_loss: 0.4551 - val_department_output_accuracy: 0.7557 - val_department_output_loss: 0.6159 - val_loss: 1.0745
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8834 - attrition_output_loss: 0.3143 - department_output_accuracy: 0.7870 - department_output_loss: 0.5493 - loss: 0.8637 - val_attrition_output_accuracy: 0.8326 - val_attrition_output_loss: 0.4638 - val_department_output_accuracy: 0.7557 - val_department_output_loss: 0.6236 - val_loss: 1.0911
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8937 - attrition_output_loss: 0.2987 - department_output_accuracy: 0.7849 - department_output_loss: 0.5326 - loss: 0.8314 - val_attrition_output_accuracy: 0.8326 - val_attrition_output_loss: 0.4673 - val_department_output_accuracy: 0.7557 - val_department_output_loss: 0.6169 - val_loss: 1.0878
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - attrition_output_accuracy: 0.8830 - attrition_output_loss: 0.3089 - department_output_accuracy: 0.7975 - department_output_loss: 0.4966 - loss: 0.8047 - val_attrition_output_accuracy: 0.8326 - val_attrition_output_loss: 0.4735 - val_department_output_accuracy: 0.7557 - val_department_output_loss: 0.6181 - val_loss: 1.0955
Epoch 9/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - attrition_output_accuracy: 0.8712 - attrition_output_loss: 0.3035 - department_output_accuracy: 0.7852 - department_output_loss: 0.4907 - loss: 0.7939 - val_attrition_output_accuracy: 0.8371 - val_attrition_output_loss: 0.4890 - val_department_output_accuracy: 0.7511 - val_department_output_loss: 0.6219 - val_loss: 1.1148
Epoch 10/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - attrition_output_accuracy: 0.8892 - attrition_output_loss: 0.3038 - department_output_accuracy: 0.7913 - department_output_loss: 0.4847 - loss: 0.7881 - val_attrition_output_accuracy: 0.8326 - val_attrition_output_loss: 0.4707 - val_department_output_accuracy: 0.7466 - val_department_output_loss: 0.6235 - val_loss: 1.0980
Epoch 11/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - attrition_output_accuracy: 0.8932 - attrition_output_loss: 0.2862 - department_output_accuracy: 0.7904 - department_output_loss: 0.4774 - loss: 0.7634 - val_attrition_output_accuracy: 0.8326 - val_attrition_output_loss: 0.4853 - val_department_output_accuracy: 0.7466 - val_department_output_loss: 0.6261 - val_loss: 1.1152
Epoch 12/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - attrition_output_accuracy: 0.8903 - attrition_output_loss: 0.2788 - department_output_accuracy: 0.7996 - department_output_loss: 0.4689 - loss: 0.7475 - val_attrition_output_accuracy: 0.8281 - val_attrition_output_loss: 0.4830 - val_department_output_accuracy: 0.7466 - val_department_output_loss: 0.6255 - val_loss: 1.1123
Epoch 13/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8988 - attrition_output_loss: 0.2896 - department_output_accuracy: 0.7805 - department_output_loss: 0.4893 - loss: 0.7791 - val_attrition_output_accuracy: 0.8281 - val_attrition_output_loss: 0.5385 - val_department_output_accuracy: 0.7466 - val_department_output_loss: 0.6357 - val_loss: 1.1781
Epoch 14/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8956 - attrition_output_loss: 0.2878 - department_output_accuracy: 0.8100 - department_output_loss: 0.4355 - loss: 0.7233 - val_attrition_output_accuracy: 0.8326 - val_attrition_output_loss: 0.4910 - val_department_output_accuracy: 0.7466 - val_department_output_loss: 0.6364 - val_loss: 1.1314
Epoch 15/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9007 - attrition_output_loss: 0.2517 - department_output_accuracy: 0.7938 - department_output_loss: 0.4745 - loss: 0.7262 - val_attrition_output_accuracy: 0.8281 - val_attrition_output_loss: 0.5029 - val_department_output_accuracy: 0.7376 - val_department_output_loss: 0.6330 - val_loss: 1.1398
Epoch 16/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9019 - attrition_output_loss: 0.2379 - department_output_accuracy: 0.8080 - department_output_loss: 0.4567 - loss: 0.6948 - val_attrition_output_accuracy: 0.8371 - val_attrition_output_loss: 0.4999 - val_department_output_accuracy: 0.7466 - val_department_output_loss: 0.6427 - val_loss: 1.1470
Epoch 17/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9071 - attrition_output_loss: 0.2227 - department_output_accuracy: 0.7924 - department_output_loss: 0.4493 - loss: 0.6717 - val_attrition_output_accuracy: 0.8190 - val_attrition_output_loss: 0.4952 - val_department_output_accuracy: 0.7511 - val_department_output_loss: 0.6489 - val_loss: 1.1487
Epoch 18/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9056 - attrition_output_loss: 0.2519 - department_output_accuracy: 0.8196 - department_output_loss: 0.4425 - loss: 0.6944 - val_attrition_output_accuracy: 0.8235 - val_attrition_output_loss: 0.4955 - val_department_output_accuracy: 0.7511 - val_department_output_loss: 0.6515 - val_loss: 1.1516
Epoch 19/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8982 - attrition_output_loss: 0.2488 - department_output_accuracy: 0.8103 - department_output_loss: 0.4214 - loss: 0.6701 - val_attrition_output_accuracy: 0.8281 - val_attrition_output_loss: 0.5357 - val_department_output_accuracy: 0.7421 - val_department_output_loss: 0.6613 - val_loss: 1.2015
Epoch 20/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9096 - attrition_output_loss: 0.2255 - department_output_accuracy: 0.8225 - department_output_loss: 0.4167 - loss: 0.6419 - val_attrition_output_accuracy: 0.8462 - val_attrition_output_loss: 0.5066 - val_department_output_accuracy: 0.7466 - val_department_output_loss: 0.6594 - val_loss: 1.1710
Epoch 21/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9158 - attrition_output_loss: 0.2319 - department_output_accuracy: 0.8309 - department_output_loss: 0.3919 - loss: 0.6236 - val_attrition_output_accuracy: 0.8326 - val_attrition_output_loss: 0.5243 - val_department_output_accuracy: 0.7330 - val_department_output_loss: 0.6554 - val_loss: 1.1845
Epoch 22/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9064 - attrition_output_loss: 0.2295 - department_output_accuracy: 0.8308 - department_output_loss: 0.4024 - loss: 0.6312 - val_attrition_output_accuracy: 0.8326 - val_attrition_output_loss: 0.5303 - val_department_output_accuracy: 0.7330 - val_department_output_loss: 0.6576 - val_loss: 1.1928
Epoch 23/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9110 - attrition_output_loss: 0.2410 - department_output_accuracy: 0.8242 - department_output_loss: 0.4058 - loss: 0.6468 - val_attrition_output_accuracy: 0.8371 - val_attrition_output_loss: 0.5279 - val_department_output_accuracy: 0.7376 - val_department_output_loss: 0.6607 - val_loss: 1.1936
Epoch 24/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9257 - attrition_output_loss: 0.2046 - department_output_accuracy: 0.8362 - department_output_loss: 0.3792 - loss: 0.5837 - val_attrition_output_accuracy: 0.8235 - val_attrition_output_loss: 0.5340 - val_department_output_accuracy: 0.7285 - val_department_output_loss: 0.6789 - val_loss: 1.2181
Epoch 25/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.9151 - attrition_output_loss: 0.2161 - department_output_accuracy: 0.8452 - department_output_loss: 0.3718 - loss: 0.5881 - val_attrition_output_accuracy: 0.8235 - val_attrition_output_loss: 0.5441 - val_department_output_accuracy: 0.7421 - val_department_output_loss: 0.6800 - val_loss: 1.2293
Epoch 26/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9201 - attrition_output_loss: 0.1859 - department_output_accuracy: 0.8465 - department_output_loss: 0.3702 - loss: 0.5559 - val_attrition_output_accuracy: 0.8190 - val_attrition_output_loss: 0.5566 - val_department_output_accuracy: 0.7376 - val_department_output_loss: 0.6876 - val_loss: 1.2492
Epoch 27/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.9247 - attrition_output_loss: 0.2006 - department_output_accuracy: 0.8526 - department_output_loss: 0.3471 - loss: 0.5477 - val_attrition_output_accuracy: 0.8281 - val_attrition_output_loss: 0.5618 - val_department_output_accuracy: 0.7376 - val_department_output_loss: 0.6822 - val_loss: 1.2491
Epoch 28/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.9412 - attrition_output_loss: 0.1914 - department_output_accuracy: 0.8580 - department_output_loss: 0.3475 - loss: 0.5389 - val_attrition_output_accuracy: 0.8281 - val_attrition_output_loss: 0.5842 - val_department_output_accuracy: 0.7466 - val_department_output_loss: 0.6933 - val_loss: 1.2825
Epoch 29/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9281 - attrition_output_loss: 0.1986 - department_output_accuracy: 0.8546 - department_output_loss: 0.3523 - loss: 0.5510 - val_attrition_output_accuracy: 0.8371 - val_attrition_output_loss: 0.5897 - val_department_output_accuracy: 0.7376 - val_department_output_loss: 0.7156 - val_loss: 1.3103
Epoch 30/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9265 - attrition_output_loss: 0.2071 - department_output_accuracy: 0.8752 - department_output_loss: 0.3296 - loss: 0.5362 - val_attrition_output_accuracy: 0.8326 - val_attrition_output_loss: 0.6054 - val_department_output_accuracy: 0.7511 - val_department_output_loss: 0.7099 - val_loss: 1.3208
Epoch 31/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9348 - attrition_output_loss: 0.1724 - department_output_accuracy: 0.8767 - department_output_loss: 0.3138 - loss: 0.4862 - val_attrition_output_accuracy: 0.8100 - val_attrition_output_loss: 0.6173 - val_department_output_accuracy: 0.7149 - val_department_output_loss: 0.7200 - val_loss: 1.3423
Epoch 32/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9342 - attrition_output_loss: 0.1694 - department_output_accuracy: 0.8770 - department_output_loss: 0.3357 - loss: 0.5044 - val_attrition_output_accuracy: 0.8145 - val_attrition_output_loss: 0.6079 - val_department_output_accuracy: 0.7376 - val_department_output_loss: 0.7423 - val_loss: 1.3554
Epoch 33/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.9469 - attrition_output_loss: 0.1646 - department_output_accuracy: 0.8832 - department_output_loss: 0.3000 - loss: 0.4649 - val_attrition_output_accuracy: 0.8054 - val_attrition_output_loss: 0.6303 - val_department_output_accuracy: 0.7240 - val_department_output_loss: 0.7329 - val_loss: 1.3686
Epoch 34/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9527 - attrition_output_loss: 0.1481 - department_output_accuracy: 0.8594 - department_output_loss: 0.3379 - loss: 0.4856 - val_attrition_output_accuracy: 0.8100 - val_attrition_output_loss: 0.6481 - val_department_output_accuracy: 0.7285 - val_department_output_loss: 0.7255 - val_loss: 1.3789
Epoch 35/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9383 - attrition_output_loss: 0.1749 - department_output_accuracy: 0.8735 - department_output_loss: 0.3139 - loss: 0.4887 - val_attrition_output_accuracy: 0.8235 - val_attrition_output_loss: 0.6455 - val_department_output_accuracy: 0.7104 - val_department_output_loss: 0.7492 - val_loss: 1.4003
Epoch 36/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9529 - attrition_output_loss: 0.1451 - department_output_accuracy: 0.8861 - department_output_loss: 0.2842 - loss: 0.4292 - val_attrition_output_accuracy: 0.8054 - val_attrition_output_loss: 0.6682 - val_department_output_accuracy: 0.7240 - val_department_output_loss: 0.7500 - val_loss: 1.4239
Epoch 37/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9536 - attrition_output_loss: 0.1447 - department_output_accuracy: 0.8701 - department_output_loss: 0.2989 - loss: 0.4437 - val_attrition_output_accuracy: 0.8054 - val_attrition_output_loss: 0.6758 - val_department_output_accuracy: 0.7285 - val_department_output_loss: 0.7962 - val_loss: 1.4770
Epoch 38/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.9616 - attrition_output_loss: 0.1340 - department_output_accuracy: 0.8996 - department_output_loss: 0.2904 - loss: 0.4245 - val_attrition_output_accuracy: 0.8100 - val_attrition_output_loss: 0.6854 - val_department_output_accuracy: 0.7149 - val_department_output_loss: 0.7560 - val_loss: 1.4469
Epoch 39/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9534 - attrition_output_loss: 0.1329 - department_output_accuracy: 0.8905 - department_output_loss: 0.2791 - loss: 0.4118 - val_attrition_output_accuracy: 0.8054 - val_attrition_output_loss: 0.6899 - val_department_output_accuracy: 0.7285 - val_department_output_loss: 0.7941 - val_loss: 1.4899
Epoch 40/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9658 - attrition_output_loss: 0.1321 - department_output_accuracy: 0.8886 - department_output_loss: 0.2779 - loss: 0.4101 - val_attrition_output_accuracy: 0.8009 - val_attrition_output_loss: 0.7032 - val_department_output_accuracy: 0.7195 - val_department_output_loss: 0.8069 - val_loss: 1.5161
Epoch 41/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9528 - attrition_output_loss: 0.1441 - department_output_accuracy: 0.8933 - department_output_loss: 0.2701 - loss: 0.4141 - val_attrition_output_accuracy: 0.8009 - val_attrition_output_loss: 0.7178 - val_department_output_accuracy: 0.7059 - val_department_output_loss: 0.8027 - val_loss: 1.5267
Epoch 42/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9611 - attrition_output_loss: 0.1299 - department_output_accuracy: 0.9059 - department_output_loss: 0.2742 - loss: 0.4041 - val_attrition_output_accuracy: 0.8054 - val_attrition_output_loss: 0.7440 - val_department_output_accuracy: 0.7195 - val_department_output_loss: 0.8265 - val_loss: 1.5761
Epoch 43/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9594 - attrition_output_loss: 0.1181 - department_output_accuracy: 0.8795 - department_output_loss: 0.2644 - loss: 0.3825 - val_attrition_output_accuracy: 0.8145 - val_attrition_output_loss: 0.7607 - val_department_output_accuracy: 0.7059 - val_department_output_loss: 0.8137 - val_loss: 1.5807
Epoch 44/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9623 - attrition_output_loss: 0.1280 - department_output_accuracy: 0.9055 - department_output_loss: 0.2655 - loss: 0.3935 - val_attrition_output_accuracy: 0.8100 - val_attrition_output_loss: 0.7776 - val_department_output_accuracy: 0.7104 - val_department_output_loss: 0.8518 - val_loss: 1.6353
Epoch 45/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9667 - attrition_output_loss: 0.1112 - department_output_accuracy: 0.9070 - department_output_loss: 0.2490 - loss: 0.3600 - val_attrition_output_accuracy: 0.8009 - val_attrition_output_loss: 0.7888 - val_department_output_accuracy: 0.7149 - val_department_output_loss: 0.8318 - val_loss: 1.6275
Epoch 46/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.9634 - attrition_output_loss: 0.1141 - department_output_accuracy: 0.9180 - department_output_loss: 0.2436 - loss: 0.3576 - val_attrition_output_accuracy: 0.7919 - val_attrition_output_loss: 0.7978 - val_department_output_accuracy: 0.7240 - val_department_output_loss: 0.8566 - val_loss: 1.6609
Epoch 47/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9641 - attrition_output_loss: 0.1137 - department_output_accuracy: 0.9133 - department_output_loss: 0.2230 - loss: 0.3367 - val_attrition_output_accuracy: 0.7873 - val_attrition_output_loss: 0.7900 - val_department_output_accuracy: 0.7059 - val_department_output_loss: 0.8646 - val_loss: 1.6614
Epoch 48/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.9532 - attrition_output_loss: 0.1124 - department_output_accuracy: 0.9170 - department_output_loss: 0.2293 - loss: 0.3415 - val_attrition_output_accuracy: 0.7964 - val_attrition_output_loss: 0.8151 - val_department_output_accuracy: 0.7059 - val_department_output_loss: 0.8711 - val_loss: 1.6935
Epoch 49/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.9667 - attrition_output_loss: 0.1025 - department_output_accuracy: 0.8964 - department_output_loss: 0.2442 - loss: 0.3468 - val_attrition_output_accuracy: 0.7919 - val_attrition_output_loss: 0.8516 - val_department_output_accuracy: 0.7059 - val_department_output_loss: 0.8829 - val_loss: 1.7411
Epoch 50/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.9747 - attrition_output_loss: 0.0906 - department_output_accuracy: 0.9032 - department_output_loss: 0.2284 - loss: 0.3191 - val_attrition_output_accuracy: 0.7919 - val_attrition_output_loss: 0.8482 - val_department_output_accuracy: 0.7195 - val_department_output_loss: 0.9076 - val_loss: 1.7627
Epoch 51/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - attrition_output_accuracy: 0.9780 - attrition_output_loss: 0.0925 - department_output_accuracy: 0.9107 - department_output_loss: 0.2161 - loss: 0.3085 - val_attrition_output_accuracy: 0.7964 - val_attrition_output_loss: 0.8869 - val_department_output_accuracy: 0.7195 - val_department_output_loss: 0.8928 - val_loss: 1.7864
Epoch 52/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - attrition_output_accuracy: 0.9736 - attrition_output_loss: 0.0808 - department_output_accuracy: 0.9031 - department_output_loss: 0.2313 - loss: 0.3120 - val_attrition_output_accuracy: 0.7873 - val_attrition_output_loss: 0.8788 - val_department_output_accuracy: 0.7285 - val_department_output_loss: 0.9242 - val_loss: 1.8100
Epoch 53/100

In [19]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test_scaled, [y_test_dept_encoded, y_test_attrition_encoded])

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8136 - attrition_output_loss: 1.3241 - department_output_accuracy: 0.6932 - department_output_loss: 1.5979 - loss: 2.9313

In [21]:
# Print the accuracy for both department and attrition
test_results = model.evaluate(X_test_scaled, [y_test_dept_encoded, y_test_attrition_encoded])

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - attrition_output_accuracy: 0.8136 - attrition_output_loss: 1.3241 - department_output_accuracy: 0.6932 - department_output_loss: 1.5979 - loss: 2.9313

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Yes. The accuracy is the best metric because it tells us how much the prediction would be correct and it also shows the loss
2. The activation functions I used the initial layers are relu. This is for the input and hidden layers. For the final output layers, I used softmax as there are multiple outputs (department, attrition ) .
3.The model can be improved by adding more hidden layers which will improve the accuracy output. Also, by running more epochs loss can be reduced a bit more which will improve the overall model.